{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "run",
    "label": "Run",
    "query": {
     "query": "SELECT \"run\" FROM \"runs\""
    }
   },
   {
    "name": "peers",
    "label": "Peers",
    "query": {
     "query": "SELECT \"id\" FROM \"$run\".\"autogen\".\"peer_online\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Train Loss",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "model_training",
     "query": "SELECT \"loss\",\"age\",\"peer_id\" FROM \"$run\".\"autogen\".\"model_training\" WHERE $timeFilter AND peer_id =~ /${peers:regex}/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eval Loss",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "model_training",
     "query": "SELECT \"loss\",\"age\",\"peer_id\" FROM \"$run\".\"autogen\".\"model_evaluation\" WHERE $timeFilter AND peer_id =~ /${peers:regex}/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "nodeGraph",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"id\", LAST(\"age\") FROM \"$run\".\"autogen\".\"peer_online\" WHERE peer_id =~ /${peers:regex}/ GROUP BY peer_id"
    },
    {
     "query": "SELECT \"source\", \"target\"\nFROM \"$run\".\"autogen\".\"peer_send\"\nWHERE $timeFilter\nAND peer_id =~ /${peers:regex}/\nGROUP BY peer_id\n"
    }
   ]
  },
  {
   "title": "Eval Accuracy",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "model_training",
     "query": "SELECT \"accuracy\",\"age\",\"peer_id\" FROM \"$run\".\"autogen\".\"model_evaluation\" WHERE $timeFilter AND peer_id =~ /${peers:regex}/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Peers",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "SELECT LAST(\"peers\") FROM \"$run\".\"autogen\".\"peer_active\" WHERE $timeFilter GROUP BY peer_id"
    }
   ]
  }
 ]
}