# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: peer-model.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ModelRequest(betterproto.Message):
    """Request message sent to the model"""

    export_weights: "ExportWeightsRequest" = betterproto.message_field(
        1, group="request"
    )
    import_weights: "ImportWeightsRequest" = betterproto.message_field(
        2, group="request"
    )
    train: "TrainRequest" = betterproto.message_field(3, group="request")
    eval: "EvalRequest" = betterproto.message_field(4, group="request")


@dataclass
class ExportWeightsRequest(betterproto.Message):
    pass


@dataclass
class ImportWeightsRequest(betterproto.Message):
    weights: bytes = betterproto.bytes_field(1)
    weight_ratio: float = betterproto.float_field(2)


@dataclass
class TrainRequest(betterproto.Message):
    pass


@dataclass
class EvalRequest(betterproto.Message):
    pass


@dataclass
class Ack(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass
class ModelResponse(betterproto.Message):
    """Response message from the model"""

    success: bool = betterproto.bool_field(1)
    error_message: str = betterproto.string_field(2)
    weights: bytes = betterproto.bytes_field(3)
    loss: float = betterproto.float_field(4)
    accuracy: float = betterproto.float_field(5)
