---
title: Incoming gradients
---
graph TB
	start(New gradients)
	done(Done)
	known{Known peer?}
	eval[Evaluate]
	good{Model improved?}
	scoreUp[Increase peer score]
	scoreDown[Decrease peer score]
	apply[Apply gradients]

	start-->known
	known-->|no|done
	known-->|yes|eval
	eval-->good
	good-->|yes|scoreUp
	good-->|no|scoreDown
	scoreDown-->done
	scoreUp-->apply
	apply-->done