---
title: Peer Acquisition
config:
  theme: neutral
  flowchart:
    curve: cardinal
---
graph LR
  start[Start]
  done[Done]
  d1{"len(ActiveSet) == N?"}
  gtrack["Get peers from tracker"]
  gpex["Get peers from PeX"]
  ginact["Promote from inactive peers"]
  start-->d1
  d1-->|"no (1)"|gtrack
  gtrack-->d1
  d1-->|"no (2)"|gpex
  gpex-->d1
  d1-->|"no (3)"|ginact
  ginact-->d1
  d1-->|"yes | no (4)"|done