apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    user: admin
    access: proxy
    url: http://influx:8181
    jsonData:
      version: SQL
      dbName: btml
      httpMode: GET
      insecureGrpc: true
    editable: true
